### ISSUE TITLE
好像用不了了？

### ISSUE THREAD

**Issue by niepan11** [Mythologyli/jd-price-check#3]
感谢大佬的代码。请问一下目前是失效了还是我的配置有误呢？
proxy没有填
corpid 填的是网页进入企业微信 --> 我的企业 -->企业ID
其他的填的应该没有问题

返回提示 完成检查
但是微信没有收到信息。
使用 另一个项目 [WeChatPusher](https://github.com/Mythologyli/WeChatPusher)的test.py却可以收到信息

**Comment by Mythologyli** [comment]
没收到信息是正常的，只有价格发生变化的时候才会收到信息
